---
title: "One Medical"
author: "Sanjay Basu"
date: "8/6/2019"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

##Import dependencies/packages

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, warning = FALSE, message = FALSE, cache.lazy = FALSE)
# install.packages('tidyverse', repos = "http://cran.us.r-project.org")
# install.packages('lubridate', repos = "http://cran.us.r-project.org")
# install.packages('readr', repos = "http://cran.us.r-project.org")
# install.packages('stringr', repos = "http://cran.us.r-project.org")
# install.packages('tableone', repos = "http://cran.us.r-project.org")
# install.packages('MatchIt', repos = "http://cran.us.r-project.org")
# install.packages('devtools', repos = "http://cran.us.r-project.org")
# install.packages('stargazer', repos = "http://cran.us.r-project.org")
# devtools::install_github("healthactuary/cmshcc")
library(tidyverse)
library(lubridate)
library(readr)
library(stringr)
library(tableone)
library(tools)
library(MatchIt)
library(cmshcc)
library(stargazer)
```

##Import datasets

```{r warning = FALSE, message = FALSE}
setwd("~/Box/Analytics Team/Research/Research projects/One medical")
mbr <- read_csv("spacex_members.csv")
clm <- read_csv("spacex_claims.csv")
rx <- read_csv("spacex_pharmacy.csv")
ctr <- read_csv("SpaceX Health Center Claims 1016 to 1217.csv")
vrt <- read_csv("SpaceX Member Virtual Services 0721919.csv")
feesch <- read_csv("FeesRVU_by_CPT_01_20190723_140220_392625.csv")
```

##Custom functions

```{r cust}

getmode <- function(v) {
   force(v)
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

```

##Format claims to combine CH claims to OM Center claims  

```{r ch plus center}
clm_dol = clm
clm_dol$`Metaclaims Analytics Medical Paid Amount Ch` = as.numeric(gsub("[\\$,]", "", clm_dol$`Metaclaims Analytics Medical Paid Amount Ch`))
clm_dol$`Metaclaims Analytics Medical First Name` = str_to_title(clm_dol$`Metaclaims Analytics Medical First Name`)
clm_dol$`Metaclaims Analytics Medical Last Name` = str_to_title(clm_dol$`Metaclaims Analytics Medical Last Name`)

clm_sub = clm_dol %>%
  mutate(personid = (`Metaclaims Analytics Medical Person ID`),
         female = (`Metaclaims Analytics Medical Gender`=="F"),
         firstname = `Metaclaims Analytics Medical First Name`,
         lastname = `Metaclaims Analytics Medical Last Name`,
         pos = `Metaclaims Analytics Medical Service Category Detail Ch`,
         dos = `Metaclaims Analytics Medical Service Date Start Ch Date`,
         om_flag = ((`Metaclaims Analytics Medical Billing Prov Bill ID`=="460695495")&(`Metaclaims Analytics Medical Billing Prov Npi`==1467701821))|
                   ((`Metaclaims Analytics Medical Billing Prov Bill ID`=="460741732")&(`Metaclaims Analytics Medical Billing Prov Npi`==1073862256))|
                   ((`Metaclaims Analytics Medical Billing Prov Bill ID`=="362169147")&(`Metaclaims Analytics Medical Billing Prov Npi`==1336709112))|
                   ((`Metaclaims Analytics Medical Billing Prov Bill ID`=="814542216")&(`Metaclaims Analytics Medical Billing Prov Npi`==1518438712))|
                   ((`Metaclaims Analytics Medical Billing Prov Bill ID`=="383906267")&(`Metaclaims Analytics Medical Billing Prov Npi`==1528538774))|
                   ((`Metaclaims Analytics Medical Billing Prov Bill ID`=="471708588")&(`Metaclaims Analytics Medical Billing Prov Npi`==1184014854))|
                   ((`Metaclaims Analytics Medical Billing Prov Bill ID`=="271346767")&(`Metaclaims Analytics Medical Billing Prov Npi`==1467781641))|
                   ((`Metaclaims Analytics Medical Billing Prov Bill ID`=="911942315")&(`Metaclaims Analytics Medical Billing Prov Npi`==1073553947))|
                   ((`Metaclaims Analytics Medical Billing Prov Bill ID`=="812141065")&(`Metaclaims Analytics Medical Billing Prov Npi`==1467800383))|
                   ((`Metaclaims Analytics Medical Billing Prov Bill ID`=="452282261")&(`Metaclaims Analytics Medical Billing Prov Npi`==1962798645))|
                   ((`Metaclaims Analytics Medical Billing Prov Bill ID`=="273009385")&(`Metaclaims Analytics Medical Billing Prov Npi`==1861709487))|
                   ((`Metaclaims Analytics Medical Billing Prov Bill ID`=="812980907")&(`Metaclaims Analytics Medical Billing Prov Npi`==1598214397))|
                   ((`Metaclaims Analytics Medical Billing Prov Bill ID`=="270243800")&(`Metaclaims Analytics Medical Billing Prov Npi`==1144457151))|
                   ((`Metaclaims Analytics Medical Billing Prov Bill ID`=="020619758")&(`Metaclaims Analytics Medical Billing Prov Npi`==1497786883))|
                   ((`Metaclaims Analytics Medical Billing Prov Bill ID`=="461773122")&(`Metaclaims Analytics Medical Billing Prov Npi`==1508103169))|
                   ((`Metaclaims Analytics Medical Billing Prov Bill ID`=="800925565")&(`Metaclaims Analytics Medical Billing Prov Npi`==1417382102))|
                   ((`Metaclaims Analytics Medical Billing Prov Bill ID`=="800925565")&(`Metaclaims Analytics Medical Billing Prov Npi`==1922470392)),
         em_flag = ((`Metaclaims Analytics Medical Procedure Code`=='99201')|
                    (`Metaclaims Analytics Medical Procedure Code`=='99202')|
                    (`Metaclaims Analytics Medical Procedure Code`=='99203')|
                    (`Metaclaims Analytics Medical Procedure Code`=='99204')|
                    (`Metaclaims Analytics Medical Procedure Code`=='99205')|
                    (`Metaclaims Analytics Medical Procedure Code`=='99211')|
                    (`Metaclaims Analytics Medical Procedure Code`=='99212')|
                    (`Metaclaims Analytics Medical Procedure Code`=='99213')|
                    (`Metaclaims Analytics Medical Procedure Code`=='99214')|
                    (`Metaclaims Analytics Medical Procedure Code`=='99215'))) %>%
  group_by(firstname,lastname,female,pos) %>%
  summarise(om_flag = as.logical(getmode(om_flag)),
            em_flag = as.logical(getmode(em_flag)),
            diag1 = getmode(`Metaclaims Analytics Medical Principal Diag`),
            cost_md = sum(`Metaclaims Analytics Medical Paid Amount Ch`),
            cnt_flag = 0) %>%
  ungroup() 

ctr_sub = ctr
ctr_sub$Name = str_to_title(ctr$Name)
ctr_sub$Name = toTitleCase(ctr$Name)
ctr_sub$`Primary Diagnosis` = as.character(gsub("[\\.]", "", ctr_sub$`Primary Diagnosis`))

ctr_sub = ctr_sub %>%
  separate("Name",c("lastname","empty","firstname"),sep = "([\\, \\ ])", extra="drop", warn = "left") %>%
  mutate(dos = mdy(DOS)) %>%
  group_by(firstname,lastname,Gender,Billing)%>%
  mutate(female= getmode((Gender=='F')),
         om_flag = as.logical(1),
         em_flag = ((CPT=='99201')|
                    (CPT=='99202')|
                    (CPT=='99203')|
                    (CPT=='99204')|
                    (CPT=='99205')|
                    (CPT=='99211')|
                    (CPT=='99212')|
                    (CPT=='99213')|
                    (CPT=='99214')|
                    (CPT=='99215')),
         pt_flag = ((Billing=='KSPANGENBE[109557787]')|
                    (Billing=='MMARCUCCIL[109565213]')),
         mh_flag = ((Billing=='Darling[109701110]')|
                      (Billing=='GFRANK[109571370]')),
         diag1 = getmode(`Primary Diagnosis`),
         pos = ("Office Visits - PCP"))  %>%  
  select(firstname,lastname,female,em_flag,om_flag,diag1,pos,CPT,pt_flag,mh_flag) %>%
  ungroup() 

ctr_sub$pos[ctr_sub$mh_flag==1] = "Mental Health and Substance Use" 
ctr_sub$pos[ctr_sub$pt_flag==1] = "Physical Medicine" 


feesch_sub = feesch %>%
  mutate(cost_md = Fee) %>%
  select(CPT,cost_md)

ctr_sub = full_join(ctr_sub,feesch_sub,by="CPT") %>%  
  select(-CPT) %>%
  mutate(cnt_flag = 1)



```

## OM attribution and utilization counts
  
```{r elig clm}

clm_tot = bind_rows(clm_sub,ctr_sub) 
  
clm_tot = clm_tot %>%
  group_by(firstname, lastname,female) %>%
  filter(any(em_flag==1)) %>%
  summarise(om_flag = getmode(om_flag[em_flag==1]),
            diag1 = getmode(diag1),
            cost_md = sum(cost_md),
            count_er = sum(pos=="Emergency Room"),
            cost_er = sum(cost_md[pos=="Emergency Room"]),
            count_hosp = sum(pos=="Inpatient Visits"),
            cost_hosp = sum(cost_md[pos=="Inpatient Visits"]),
            count_pcp = sum((pos=="Office Visits - PCP")|(pos=="Preventive Visits - PCP")),
            cost_pcp = sum((cost_md[pos=="Office Visits - PCP"|pos=="Preventive Visits - PCP"])),
            count_spec = sum((pos=="Office Visits - Specialist")|(pos=="Preventive Visits - Specialist")),
            cost_spec = sum((cost_md[pos=="Office Visits - Specialist"|pos=="Preventive Visits - Specialist"])),
            count_mh = sum(pos=="Mental Health and Substance Use"),
            cost_mh = sum(cost_md[pos=="Mental Health and Substance Use"]),
            count_pt = sum(pos=="Physical Medicine"),
            cost_pt = sum(cost_md[pos=="Physical Medicine"]),
            cnt_flag = max(cnt_flag)) %>%   
  select(firstname,lastname, female,om_flag,diag1,cost_md,count_er,cost_er,count_hosp,cost_hosp,count_pcp,cost_pcp,count_spec,cost_spec,count_mh,cost_mh,count_pt,cost_pt,cnt_flag) %>%
  ungroup()
clm_tot$female[is.na(clm_tot$female)==1]=0


```

##Member org

```{r elig mbr}
mbr_sub = mbr
mbr_sub$`Analytics Member Months First Name` = str_to_title(mbr_sub$`Analytics Member Months First Name`)
mbr_sub$`Analytics Member Months Last Name` = str_to_title(mbr_sub$`Analytics Member Months Last Name`)

mbr_sub = mbr_sub %>%
  mutate(personid = `Analytics Member Months Person ID`) %>%
  group_by(personid) %>%
  mutate(start = min(`Analytics Member Months Start Date`),
         end = max(`Analytics Member Months End Date`),
         age = mean(`Analytics Member Months Age`),
         female = (`Analytics Member Months Gender`=='F'),
         firstname = `Analytics Member Months First Name`,
         lastname = `Analytics Member Months Last Name`,
         membermo = interval(start,end)/months(1),
         DOB = `Analytics Member Months Date of Birth Date`) %>%
  select(age, female, personid, firstname, lastname, membermo, DOB) %>%
  distinct()
```

##Add in pharmacy claims  

```{r elig rx}
rx_dol = rx
rx_dol$`Analytics Claims Pharmacy Paid Amount` = as.numeric(gsub("[\\$,]", "", rx_dol$`Analytics Claims Pharmacy Paid Amount`))
rx_dol$`Analytics Claims Pharmacy First Name` = str_to_title(rx_dol$`Analytics Claims Pharmacy First Name`)
rx_dol$`Analytics Claims Pharmacy Last Name` = str_to_title(rx_dol$`Analytics Claims Pharmacy Last Name`)

rx_sub = rx_dol %>%
  mutate(personid = `Analytics Claims Pharmacy Person ID`) %>%
  group_by(personid) %>%
  mutate(female = (`Analytics Claims Pharmacy Gender`=="F"),
         firstname = `Analytics Claims Pharmacy First Name`,
         lastname = `Analytics Claims Pharmacy Last Name`,
         cost_rx = sum(`Analytics Claims Pharmacy Paid Amount`)) %>%
  select(female, personid, firstname,lastname,cost_rx) %>%
  distinct()
```


##Virtual visits

```{r vrt}
vrt_sub = vrt
vrt_sub$`dphi.patient_first_name` = str_to_title(vrt_sub$`dphi.patient_first_name`)
vrt_sub$`dphi.patient_last_name` = str_to_title(vrt_sub$`dphi.patient_last_name`)

vrt_sub = vrt_sub %>%
  mutate(vrt_flag = 1,
         firstname = dphi.patient_first_name,
         lastname = dphi.patient_last_name) %>%
  select(firstname, lastname, vrt_flag) %>%
  distinct()


```

##HCC risk score

```{r hcc}

spacex_dat = mbr_sub %>% 
  full_join(clm_tot, by = c("firstname","lastname","female")) %>%
  full_join(rx_sub, by = c("firstname","lastname","female")) %>%
  full_join(vrt_sub, by = c("firstname","lastname")) %>%
  mutate(om_flag = replace_na(om_flag,0),
         vrt_flag = replace_na(vrt_flag,0),
         cnt_flag = replace_na(cnt_flag,0)) %>%
  distinct()

PERSON = spacex_dat %>%
  ungroup() %>%
  mutate(HICNO = personid.x,
         SEX = if_else(female==1,"F","M"),
         DOB = DOB,
         MCAID = 0,
         NMCAID = 0,
         OREC = 0) %>%
  select(HICNO, SEX, MCAID, NMCAID, OREC, DOB) %>% 
  filter(!is.na(HICNO))

cmshcc_map <- load_cmshcc_map()

DIAG = spacex_dat %>%
  ungroup() %>%
  mutate(HICNO = personid.x,
         DX = diag1) %>%
  select(HICNO, DX) %>% 
  filter(!is.na(HICNO))

hcc = evaluate_v22_2017(PERSON, DIAG, "Community_NonDual_Aged")


```

## CCS cat

```{r ccs}
ccs <- read_csv("ccs_dx_icd10cm_2018_1.csv")
ccs  =ccs %>%
  mutate(diag1 = `ICD-10-CM CODE`,
         ccs = `CCS CATEGORY`) %>%
  select(diag1, ccs)

```

##Pre-match

```{r na}

spacex_dat_ana = mbr_sub %>% 
  full_join(clm_tot, by = c("firstname","lastname","female")) %>%
  full_join(rx_sub, by = c("firstname","lastname","female")) %>%
  full_join(vrt_sub, by = c("firstname","lastname")) %>%
  full_join(hcc, by = c("personid.x" = "HICNO")) %>%
  left_join(ccs, c("diag1")) %>%
  mutate(age = mean(age),
         om_flag = replace_na(om_flag,0),
         vrt_flag = replace_na(vrt_flag,0),
         cnt_flag = replace_na(cnt_flag,0),
         cost_md = replace_na(cost_md,0),
         count_er = replace_na(count_er,0),
         cost_er = replace_na(cost_er,0),
         count_hosp = replace_na(count_hosp,0),
         cost_hosp = replace_na(cost_hosp,0),
         count_pcp = replace_na(count_pcp,0),
         cost_pcp = replace_na(cost_pcp,0),
         count_spec = replace_na(count_spec,0),
         cost_spec = replace_na(cost_spec,0),
         count_mh = replace_na(count_mh,0),
         count_pt = replace_na(count_pt,0),
         cost_pt = replace_na(cost_pt,0),
         cost_mh = replace_na(cost_mh,0),
         cost_rx = replace_na(cost_rx,0),
         hcc = Community_NonDual_Aged,
         hcc = replace_na(hcc,0)) %>%
  ungroup() %>%
  group_by(personid.x) %>%
  filter(membermo>0) %>%
  summarise(mm = mean(membermo,na.rm=T),
            age = mean(age, na.rm=TRUE),
            age = replace_na(age,0),
            female = mean(female, na.rm=TRUE),
            female = replace_na(female,0),
            cost_tot = (sum(cost_md, na.rm=TRUE)+sum(cost_rx, na.rm=TRUE))/mm, 
            cost_md = sum(cost_md, na.rm=TRUE)/mm, 
            cost_rx = sum(cost_rx, na.rm=TRUE)/mm, 
            cost_er = sum(cost_er, na.rm=TRUE)/mm,
            cost_hosp = sum(cost_hosp, na.rm=TRUE)/mm,
            cost_pcp = sum(cost_pcp, na.rm=TRUE)/mm,
            cost_spec = sum(cost_spec, na.rm=TRUE)/mm,
            cost_mh = sum(cost_mh, na.rm=TRUE)/mm,
            cost_pt = sum(cost_pt, na.rm=TRUE)/mm,
            count_er = sum(count_er, na.rm=TRUE)/mm,
            count_hosp = sum(count_hosp, na.rm=TRUE)/mm,
            count_pcp = sum(count_pcp, na.rm=TRUE)/mm,
            count_spec = sum(count_spec, na.rm=TRUE)/mm,
            count_mh = sum(count_mh, na.rm=TRUE)/mm,
            count_pt = sum(count_pt, na.rm=TRUE)/mm,
            vrt_flag = mean(vrt_flag,na.rm=T),
            cnt_flag = mean(cnt_flag,na.rm=T),
            om_flag = mean(om_flag, na.rm=T),
            hcc = mean(hcc,na.rm=T),
            ccs = mean(ccs,na.rm=T),
            hcc = replace_na(hcc,0),
            ccs = replace_na(ccs,0),
            ccs = as.factor(ccs),
            diag1 = getmode(`diag1`),
            diag1 = replace_na(diag1,0)) 
  


summary(spacex_dat_ana)


```

##Matching

```{r matching}
spacex_dat_cov <- c('age', 'female', 'mm', 'membermo', 'hcc', 'ccs', 'diag1')

spacex_dat_nomiss = as.data.frame(spacex_dat_ana)

start_time <- Sys.time()

spacex_dat_nomiss = spacex_dat_nomiss %>% 
  mutate(agecat = 1*(age<4) + 2*(age>=4)*(age<11) + 3*(age>=11)*(age<21)+4*(age>=21)*(age<25)+5*(age>=25)*(age<28)+6*(age>=28)*(age<30)+7*(age>=30)*(age<34)+8*(age>=34)*(age<38)+9*(age>=38)*(age<48)+10*(age>=48)*(age<79)+11*(age>=79),
         hcccat = 1*(hcc==0) + 2*(hcc>0)&(hcc<1) + 3*(hcc>=1),
         mmcat = 1*(mm<39) + 2*(mm>=39 & mm<48) + 3*(mm>=48))

set.seed(100)
mod_match <- matchit(om_flag ~ age + female + ccs + hcccat + mm,
                     method = "nearest", data = spacex_dat_nomiss)
end_time <- Sys.time()

end_time - start_time

mod_match

dta_m <- match.data(mod_match)
dim(dta_m)

dta_m %>%
  group_by(om_flag) %>%
  select(one_of(spacex_dat_cov)) %>%
  summarise_all(funs(mean))

# continuous
print(CreateTableOne(vars = c("age", "female", "hcc", "mm", "ccs"), strata = "om_flag", data = dta_m, test = T), smd = TRUE)

```

#Outcome metrics
```{r outcomes}
dta_run = dta_m %>%
  mutate(logcost_md = log(cost_md+1),
         logcost_er = log(cost_er+1),
         logcost_hosp = log(cost_hosp+1),
         logcost_pcp = log(cost_pcp+1),
         logcost_spec = log(cost_spec+1),
         logcost_mh = log(cost_mh+1),
         logcost_pt = log(cost_pt+1),
         logcost_rx = log(cost_rx+1),
        logcount_er = log(count_er+1),
        logcount_hosp = log(count_hosp+1),
        logcount_pcp = log(count_pcp+1),
        logcount_spec = log(count_spec+1),
        logcount_mh = log(count_mh+1),
        logcount_pt = log(count_pt+1),
        cost_per_er = (cost_er+1)/(count_er+1),
        cost_per_hosp = (cost_hosp+1)/(count_hosp+1),
        cost_per_pcp = (cost_pcp+1)/(count_pcp+1),
        cost_per_spec = (cost_spec+1)/(count_spec+1),
        cost_per_mh = (cost_mh+1)/(count_mh+1),
        cost_per_pt = (cost_pt+1)/(count_pt+1))
```

```{r table 1}
# pre-match
print(CreateTableOne(data =spacex_dat_ana, vars = c("age", "female", "hcc", "mm", "cost_md", "cost_rx", "cost_er" ,"cost_hosp" , "cost_pcp"  , "cost_spec"  ,"cost_mh" ,"cost_pt" ,   "count_er"  , "count_hosp" ,"count_pcp" ,"count_spec", "count_mh",   "count_pt"  , "vrt_flag" ,"cnt_flag"), strata="om_flag", test = T), smd = TRUE)

# post-match
print(CreateTableOne(data =dta_m, vars = c("age", "female", "hcc", "mm", "cost_md", "cost_rx", "cost_er" ,"cost_hosp" , "cost_pcp"  , "cost_spec"  ,"cost_mh" ,"cost_pt" ,   "count_er"  , "count_hosp" ,"count_pcp" ,"count_spec", "count_mh",   "count_pt"  , "vrt_flag" ,"cnt_flag"), strata="om_flag", test = T), smd = TRUE)



```

#Treatment effect 

```{r ate}

glmMatched1 <- glm(formula = logcost_md ~ om_flag + age + female + mm + hcc + ccs ,
                   data    = dta_run)

glmMatched2 <- glm(formula = logcost_er ~ om_flag + age + female + mm + hcc + ccs ,
                   data    = dta_run)

glmMatched3 <- glm(formula = logcost_hosp ~ om_flag + age + female + mm + hcc + ccs ,
                   data    = dta_run)

glmMatched4 <- glm(formula = logcost_pcp ~ om_flag + age + female + mm + hcc + ccs ,
                   data    = dta_run)

glmMatched5 <- glm(formula = logcost_spec ~ om_flag + age + female + mm + hcc + ccs ,
                   data    = dta_run)


glmMatched5a <- glm(formula = logcost_mh ~ om_flag + age + female + mm + hcc + ccs ,
                    data    = dta_run)


glmMatched5b <- glm(formula = logcost_pt ~ om_flag + age + female + mm + hcc + ccs ,
                    data    = dta_run)


glmMatched6 <- glm(formula = logcost_rx ~ om_flag + age + female + mm + hcc + ccs ,
                   data    = dta_run)


glmMatched7 <- glm(formula = logcount_er ~ om_flag + age + female + mm + hcc + ccs ,
                   data    = dta_run)


glmMatched8 <- glm(formula = logcount_hosp ~ om_flag + age + female + mm + hcc + ccs ,
                   data    = dta_run)


glmMatched9 <- glm(formula = logcount_pcp ~ om_flag + age + female + mm + hcc + ccs ,
                   data    = dta_run)

glmMatched10 <- glm(formula = logcount_spec ~ om_flag + age + female + mm + hcc + ccs ,
                    data    = dta_run)



glmMatched10a <- glm(formula = logcount_mh ~ om_flag + age + female + mm + hcc + ccs ,
                     data    = dta_run)



glmMatched10b <- glm(formula = logcount_pt ~ om_flag + age + female + mm + hcc + ccs ,
                     data    = dta_run)


glmMatched2c <- glm(formula = cost_per_er ~ om_flag + age + female + mm + hcc + ccs ,
                   data    = dta_run)

glmMatched3c <- glm(formula = cost_per_hosp ~ om_flag + age + female + mm + hcc + ccs ,
                   data    = dta_run)

glmMatched4c <- glm(formula = cost_per_pcp ~ om_flag + age + female + mm + hcc + ccs ,
                   data    = dta_run)

glmMatched5c <- glm(formula = cost_per_spec ~ om_flag + age + female + mm + hcc + ccs ,
                   data    = dta_run)


glmMatched5ca <- glm(formula = cost_per_mh ~ om_flag + age + female + mm + hcc + ccs ,
                    data    = dta_run)


glmMatched5cb <- glm(formula = cost_per_pt ~ om_flag + age + female + mm + hcc + ccs ,
                    data    = dta_run)

```

##Results as percentage change in each outcome


```{r coef}

exponentiate <- function(x) ((exp(x)-1)*100)

stargazer::stargazer(glmMatched1, glmMatched2, glmMatched3, glmMatched4, glmMatched5, glmMatched5a, glmMatched5b, glmMatched6,
          title="Spend Results", single.row=TRUE,
          type = "text",
          keep=c("om_flag","age","female","mm","hcc"),
          ci=TRUE, ci.level=0.95,
          apply.coef=exponentiate,
          digits = 1)

stargazer::stargazer(glmMatched7, glmMatched8, glmMatched9, glmMatched10, glmMatched10a, glmMatched10b,
          title="Utilization Results", single.row=TRUE,
          type = "text",
          keep=c("om_flag","age","female","mm","hcc"),
          ci=TRUE, ci.level=0.95,
          apply.coef=exponentiate,
          digits = 1)

stargazer::stargazer(glmMatched2c, glmMatched3c, glmMatched4c, glmMatched5c, glmMatched5ca, glmMatched5cb, 
          title="Cost per Utilization Results", single.row=TRUE,
          type = "text",
          keep=c("om_flag","age","female","mm","hcc"),
          ci=TRUE, ci.level=0.95,
          apply.coef=exponentiate,
          digits = 1)

save.image("~/Box/Analytics Team/Research/Research projects/One medical/onemedical.RData")


```
